name: Build, Test and Publish Pyinstaller Binaries

on:
  workflow_call:
    inputs:
      production_release:
        required: true
        type: string
      python_version:
        required: true
        type: string

jobs:
  build-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-14]
        include:
          - os: macos-latest
            build_command: "poetry run poe package_unix"
          - os: macos-14
            build_command: "poetry run poe package_unix"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.production_release == 'true' && '0' || '1' }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Set up Poetry
        uses: ./.github/actions/setup-poetry

      - name: Setup poetry cache
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}-${{ runner.os }}-${{ runner.arch }}-${{ inputs.python_version }}

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Install the Apple certificate
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
        env:
          BUILD_CERTIFICATE_BASE64: MIIKCwIBAzCCCdIGCSqGSIb3DQEHAaCCCcMEggm/MIIJuzCCBD8GCSqGSIb3DQEHBqCCBDAwggQsAgEAMIIEJQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIt/a/l427oekCAggAgIID+Gtxsjf9SEay1cBti/PH4BeS5pzcovFvDTU4svOR9INcr7iyuAz4HJqZG7LeCxRhDolkRAG9oqtcmcMLOvIA4CiAivpNReBxu1FrCh/5WB7Ardrj0YrWH4PxcBj1xQNz5KLbwTIvGV/ifzMpVCE+9K7xupV1XcwOvtAFrheSRC9yEeCQlSvPGS+GItS8L8zTTcrOxF2onRW3QxncTBVJ6u7O1OHpSHY53dgDHaktOUFww/OiXWiE8y5dcDRDpwDA1vlYCBAc7D69NZoXcWSavRNH+6Uq7aCwYN/aiOeagruo22FY3C2pILQ6I81vctptaMRiDSfE0oamK5ak5BYmkbAnTFpphHFQqY/0LHW8qlKUK3DoXK1kh61QhYW6k+Txr47Kwc6CxZhePRNpUSS2Sph0YRaFFmnyjGmMhNNaNN2yFWJ4dktZ0kJuLKVZaDV8gM3gO7BKwor6ng7TTFwO8pc4inPNI358MfcbCywQZfO29Q0w4I+FPaglnaiv/n8AEnW1+8g/mUJCyZ9XJK21HZhpO0PPqFTFPArN+luB1qaeCHdIHR1ePENid1AMQk8+uuVOJCKstHvlkYKaeLD76AOMozqOyiJdv2gA0ZLBkTzj3vApVXBAsytgIljPmKrfK6e6DLLekSFv1ABtQf4/C//qIoQotLqRF0premgChaRKXGAt47rCJZvTYwPHe3xpK+bXVErmf+gA1pwLS0N+Ucp753REPSU6jsciI49OUJDLn3rey74KVdToyecYUbq4g5ieRPd35UpqlN1yY/kSNQKTjUou9nBSkTbcjTpy1t6SW1Iss3UqsLWhvu92AUjiN4I3QcP+lcMvAvGvNDnPBaDo418S9XXgPYUb5Q+pU36kqHaq/YmODmeAv8Jvg3EFI8iu+FB97/CXSWinCgOLm/ZHCKJXXXzxxxKZTC3LTHQnjnDG7hwARBsZCVLoFrI4ZpQpUKqNfYyO7AhX7lePygVELQU2Mp9VEv7mtxPlTjsTdtuoubJtoeTS6s6aNrMlLPI2J390BDJxbRMafr8LeK8qDreRacfJHkMBSSOSos2qNhm8pbT8ogGjJUTsjbpUvxZ33EROe0D7UsawlIcadqSFsN1XqPgxDZU8FTZeycTSpSybPqSvN0ZPKR8upRdRlU4/X8UtfE82c/1GBz7mhRT5+SjDPk9IsrKb580fA6wyA3tEAnhf8o1/GPLJd9Q3YtlFxfoyTQbFVVaRPaH6HrJ5SdAz0vJJ9YLGpuNikj/6EMkiSIcyFMdGDouSYxFZYZgR+jkonuOith/m+L0vOCu5BSlFn284NVmQ6HNXj60r/WGf5xW4nTzPJHf0zXVzvDvXDjNZQEXtMIIFdAYJKoZIhvcNAQcBoIIFZQSCBWEwggVdMIIFWQYLKoZIhvcNAQwKAQKgggTuMIIE6jAcBgoqhkiG9w0BDAEDMA4ECML+IV9hwZ3GAgIIAASCBMjiLGRhAcQbbWaOgKd8VhPyvxXwP1YjORHuCsvRgONhoblnWJc/fssbwnq+TYbzDOmZOuj1xfnendk5xdN67Is7cKNVq5oqTjVywvJO8uVu9Ac/3wtA3I5YZlFcSdt+lo94mT0UBmVQk2WavfixaIc2PRTqrGlzyEmXKyYLTuOQk5KKkuVSv/sWyIBusX86zH2SGiDVEoJSYB19sjr8Dr49LWFgjprVMTtc1py7ty3Td+ndOaiaKq0oLD80IMnTYleSfo92CsJ9UDmYQDbJBJ2VsAvxMGNMoIM1M/5wujuXBH52lRhKu1JOsaTfvZToniGb99088pMLy5JRQBdzrjwdQJkvKWxA4lVZXTkxWV7QBZ7ol5Ym4tuJAGvTYmhZ8zdTIU58FdifX7PlUkSSGlLKs3DEx7ymelMUNPwkuK2qGeUgM3VmFpO+xaUA6kKWDRkQotUmJrQKeA4Onw5jam3rPVk993k0m/lbuTot5AJ9SmzznyY5BD+4o+zf7JaHZEqTO36E7IYQPhBXMYFCJiYgri5STKgbnwMJy/gvIVn7NCmtogmyJjT/MqLFLy0bPDWKD9loIXmXon6f65zTm4wlK/VNwD1alQA3bC9Ty1ORCJBWC2IMh8D43Cy9XuAfjkUVlhNNxlvCqOuUi/K34ihIv/UvqA6onTYd2DthR4BzZRfkMMvKWRdCu0prcyBBnPMjxFUd/OtW7HGXhTM6XMgyPY925fe7lDmYfHEdRRDzVzUH7A8JLZZ6J6e8XRM00bvRfjAfHNXBU9GemZ7EQnxbVkA9EbMGJ6Owb9JwO4/6v8oikodNmg9CJ0sQGlDTPwYXt88TzksMNoTgWZ7VUPLflT4Tsca3DhPPlqmCEdHT+0tT4PQvbizCB8U83vy6ZrRsgC5qqLDpsX1mYHpgr9aiAZWpXd7KubCV6klUHm/KX/hXPP/DKCGvNZGs5j56u+fFqq9cwTR6ACozyCunPwuBWGBH5NZeu5Kl68rb6lMbaJMX7JWyfgweSSfK3vrfAJNmE4Gn1QbPQk5IQVe2pYM76vXrpq87QXrW+niDogHa3oxAYs/mj/PkIqnkXMREFfeC0J6qEATzzR3fkdh4byozYSjCrKf1bNy3IhhbJWhftNfNd6H/JZWjjWFC1O040bQdLRfRb/WD0nz+JWurToZrll3rFntIyZVGZm8vD5cS4CrQv96zXOIkt7wGcam0EPzIiR2+YFZTlQsDH/kPmaqOwRDxnVIV0VCEuy/9PBRptUtKszFpy+gI+kRRdQ+fozdTX6bFfVmSUnUp1uVW4lL/Ml42Q40PlCq2mMLK8ePR3+/eFrCuRMQfjE+pfkk+cKx3z8RyVGMrktd6FwZ5ZIY6X14/5yhzq8srCAioiHWJSVWiTEjZrPZGtUt9pz9v1jg8Riqvg4BrQ35B8ROTjAWSWh8xasUjwP4dP7XKmn7mR2gsxn75NIqPPs+skkHJucjYU0x/QigE7P6mz8PWuxE8ymIPiSzoT339AeLM2vIvQZsrp4Edo4ff+uTP1j26udnFjbNTa/S9o8xTFi/ozY8IA+CeHId1rQO/J2OzPbnTFTYDJPp7VJHUbBZ0fwdZWqeHaXD3KI1S8Pbsyy2b5LFs3VhfdjloRTMxWDAxBgkqhkiG9w0BCRQxJB4iAGEAbABnAG8ALQBjAG8AZABlAC0AcwBpAGcAbgBpAG4AZzAjBgkqhkiG9w0BCRUxFgQUTYm74gZqKwhDjs7167sW8oE1AqUwMDAhMAkGBSsOAwIaBQAEFPV/65U3Qv4qfEoIRPBXO8UWIMUdBAjk/nbd2h8HgwIBAQ==
          P12_PASSWORD: password
          KEYCHAIN_PASSWORD: password

      - name: Build & test binary
        uses: ./.github/actions/build-binaries
        with:
          python_version: ${{ inputs.python_version }}
          package_name: "algokit"
          production_release: ${{ inputs.production_release }}
          operating_system: ${{ runner.os }}
          architecture: ${{ runner.arch }}
          build_command: ${{ matrix.build_command }}
